[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "harbinger"
version = "0.0.0"
description = "ðŸ§™ðŸ»â€â™‚ï¸ An AI agent to warn you the breaking changes caused by the API specification changes"
authors = [{ name = "Chisanan232", email = "chi10211201@cycu.org.tw" }]
requires-python = ">=3.13,<4.0"
readme = "README.md"
license = { file = "LICENSE" }
keywords = [
    "ai",
    "ai agents",
    "ai-assistents",
    "API spec checking",
    "API client helper",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/Chisanan232/Harbinger"
Repository = "https://github.com/Chisanan232/Harbinger"

[dependency-groups]
dev = [
    "pytest>=8.1.1,<9",
    "pytest-cov>=5.0.0,<8",
    "coverage~=7.10",
    "pytest-rerunfailures>=14.0,<17",
    "aiohttp>=3.12.13",
    "pytest-asyncio>=0.23.0,<2",
    "python-dotenv>=1.0.1,<2",
]
pre-commit-ci = [
    "pre-commit>=3.5.0,<5",
    "pylint>=3.1.0,<5",
    "mypy>=1.2.0,<2",
]

[tool.uv]
default-groups = [
    "dev",
    "pre-commit-ci",
]

[tool.hatch.build.targets.sdist]
include = ["harbinger/"]

[tool.hatch.build.targets.wheel]
include = ["harbinger/"]
